import { useMemo } from 'react';
import { useLocale } from "@/locales/LocaleProvider";

export const useProjects = () => {
    const { t } = useLocale();

    return useMemo(() => [
        {
            id: 18,
            category: t("services.pipeInsulation.title"),
            title: t("services.pipeInsulation.subtitle"),
            description: t("services.pipeInsulation.description"),
            video: "/images/pipe1.mp4",
            date: "01-10-2025",
        },
        {
            id: 20,
            category: t("services.pipeInsulation.title"),
            title: t("services.pipeInsulation.subtitle"),
            description: t("services.pipeInsulation.description"),
            image: "/images/pipe4.jpg",
            date: "01-10-2025",
        },
        {
            id: 19,
            category: t("services.pipeInsulation.title"),
            title: t("services.pipeInsulation.subtitle"),
            description: t("services.pipeInsulation.description"),
            video: "/images/pipe2.mp4",
            date: "01-10-2025",
        },
        {
            id: 21,
            category: t("services.pipeInsulation.title"),
            title: t("services.pipeInsulation.subtitle"),
            description: t("services.pipeInsulation.description"),
            video: "/images/pipe3.mp4",
            date: "01-10-2025",
        },
        {
            id: 22,
            category: t("services.pipeInsulation.title"),
            title: t("services.pipeInsulation.subtitle"),
            description: t("services.pipeInsulation.description"),
            image: "/images/pipe5.jpg",
            date: "01-10-2025",
        },
        {
            id: 1,
            category: t("services.repair.title"),
            title: t("services.repair.subtitle"),
            description: t("services.repair.description"),
            image: "/images/repair1.jpg",
            date: "01-10-2025",
        },
        {
            id: 2,
            category: t("services.repair.title"),
            title: t("services.repair.subtitle"),
            description: t("services.repair.description"),
            image: "/images/repair2.jpg",
            date: "01-10-2025",
        },
        {
            id: 3,
            category: t("services.repair.title"),
            title: t("services.repair.subtitle"),
            description: t("services.repair.description"),
            image: "/images/repair3.jpg",
            date: "01-10-2025",
        },
        {
            id: 4,
            category: t("services.pipeInsulation.title"),
            title: t("services.pipeInsulation.subtitle"),
            description: t("services.pipeInsulation.description"),
            image: "/images/repair4.jpg",
            date: "01-10-2025",
        },
        {
            id: 12,
            category: t("services.repair.title"),
            title: t("services.repair.subtitle"),
            description: t("services.repair.description"),
            image: "/images/repair8.jpg",
            date: "01-10-2025",
        },
        {
            id: 9,
            category: t("services.repair.title"),
            title: t("services.repair.subtitle"),
            description: t("services.repair.description"),
            image: "/images/repair13.jpg",
            date: "01-10-2025",
        },
        {
            id: 10,
            category: t("services.repair.title"),
            title: t("services.repair.subtitle"),
            description: t("services.repair.description"),
            image: "/images/repair10.jpg",
            date: "01-10-2025",
        },
        {
            id: 11,
            category: t("services.repair.title"),
            title: t("services.repair.subtitle"),
            description: t("services.repair.description"),
            image: "/images/repair11.jpg",
            date: "01-10-2025",
        },
        {
            id: 5,
            category: t("services.repair.title"),
            title: t("services.repair.subtitle"),
            description: t("services.repair.description"),
            image: "/images/repair1.jpg",
            date: "01-10-2025",
        },
        {
            id: 14,
            category: t("services.oilEquipment.title"),
            title: t("services.oilEquipment.subtitle"),
            description: t("services.oilEquipment.description"),
            image: "/images/oil1.jpg",
            date: "01-10-2025",
        },
        {
            id: 15,
            category: t("services.oilEquipment.title"),
            title: t("services.oilEquipment.subtitle"),
            description: t("services.oilEquipment.description"),
            image: "/images/oil2.jpg",
            date: "01-10-2025",
        },
        {
            id: 16,
            category: t("services.oilEquipment.title"),
            title: t("services.oilEquipment.subtitle"),
            description: t("services.oilEquipment.description"),
            image: "/images/oil3.jpg",
            date: "01-10-2025",
        },
        {
            id: 8,
            category: t("services.pipeInsulation.title"),
            title: t("services.pipeInsulation.subtitle"),
            description: t("services.pipeInsulation.description"),
            image: "/images/repair7.jpg",
            date: "01-10-2025",
        },
    ], [t]);
};